[tasks.readme]
tools."ubi:mitsuhiko/minijinja" = "latest"
usage = '''
arg "<blog_rss_url>" default="https://vrslev.com/rss.xml"
'''
run = """
curl -sSfL ${usage_blog_rss_url} \
| yq --input-format xml --output-format yaml \
'.rss.channel.item[].pubDate |= with_dtf("Mon, 02 Jan 2006 15:04:05 -0700"; format_datetime("2 January 2006"))' \
| minijinja README.md.j2 - --format yaml --strict -o README.md
"""
